# Generated by Django 4.1.3 on 2022-11-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_employee_child_id_employee_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='child_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='parent_id',
            field=models.PositiveIntegerField(),
        ),
    ]
